# Generated by Django 4.1 on 2022-08-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=25)),
                ('agency_name', models.CharField(max_length=125)),
                ('agency_url', models.URLField()),
                ('agency_timezone', models.CharField(max_length=25)),
                ('agency_lang', models.CharField(max_length=25)),
                ('agency_phone', models.CharField(max_length=30)),
                ('agency_fare_url', models.URLField()),
            ],
        ),
    ]
