# Generated by Django 4.1 on 2022-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=25)),
                ('monday', models.CharField(max_length=25)),
                ('tuesday', models.CharField(max_length=25)),
                ('wednesday', models.CharField(max_length=25)),
                ('thursday', models.CharField(max_length=25)),
                ('friday', models.CharField(max_length=25)),
                ('saturday', models.CharField(max_length=25)),
                ('sunday', models.CharField(max_length=25)),
                ('start_date', models.CharField(max_length=25)),
                ('end_date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('route_short_name', models.CharField(max_length=45)),
                ('route_long_name', models.CharField(max_length=125)),
                ('route_desc', models.CharField(max_length=125)),
                ('route_type', models.CharField(max_length=25)),
                ('route_url', models.CharField(max_length=125)),
                ('route_color', models.CharField(max_length=50)),
                ('route_text_color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.CharField(max_length=45)),
                ('shape_pt_lon', models.CharField(max_length=45)),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('stop_code', models.IntegerField()),
                ('stop_name', models.CharField(max_length=125)),
                ('stop_desc', models.CharField(max_length=100)),
                ('stop_lat', models.CharField(max_length=100)),
                ('stop_lon', models.CharField(max_length=100)),
                ('zone_id', models.IntegerField()),
                ('stop_url', models.URLField()),
                ('location_type', models.CharField(max_length=100)),
                ('parent_station', models.CharField(max_length=100)),
                ('wheelchair_boarding', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_id', models.IntegerField()),
                ('stop_sequence', models.IntegerField()),
                ('pickup_type', models.CharField(max_length=100)),
                ('drop_off_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('trip_id', models.IntegerField()),
                ('trip_headsign', models.CharField(max_length=100)),
                ('direction_id', models.CharField(max_length=100)),
                ('block_id', models.CharField(max_length=100)),
                ('shape_id', models.CharField(max_length=100)),
            ],
        ),
    ]
