# Generated by Django 4.1 on 2022-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_calendar_calendardates_routes_shapes_stops_stoptimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardates',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
