# Generated by Django 4.1 on 2022-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_calendardates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_id',
            field=models.CharField(max_length=25),
        ),
    ]
