# Generated by Django 4.1 on 2022-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_routes_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_desc',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
