# Generated by Django 4.1 on 2022-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_routes_route_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_text_color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_url',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='shapes',
            name='shape_id',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.CharField(max_length=20),
        ),
    ]
