# Generated by Django 4.1 on 2022-08-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_stops_stop_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='zone_id',
            field=models.IntegerField(null=True),
        ),
    ]
