# Generated by Django 4.1 on 2022-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_stops_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='location_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='parent_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='wheelchair_boarding',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
