# Generated by Django 4.1 on 2022-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_stops_location_type_alter_stops_parent_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='trip_id',
            field=models.CharField(max_length=75),
        ),
    ]
