# Generated by Django 4.1 on 2022-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_stoptimes_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='stop_id',
            field=models.CharField(max_length=100),
        ),
    ]
