# Generated by Django 4.1 on 2022-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_stoptimes_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='departure_time',
            field=models.CharField(max_length=100),
        ),
    ]
