# Generated by Django 4.1 on 2022-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_stoptimes_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='route_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trips',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_id',
            field=models.CharField(max_length=100),
        ),
    ]
